baseURL: 'https://jozefcipa.com'
languageCode: en-us
title: Jozef Cipa
theme: papermod
enableRobotsTXT: true
paginate: 10
summaryLength: 30
# googleAnalytics: 'UA-89527096-1'
taxonomies:
  tags: tags
params:
  description: a backend developer with a passion for IoT and automation
  images:
    - assets/meta-preview.jpg
  schema:
    publisherType: Person
  ShowReadingTime: true
  ShowShareButtons: true
  disableScrollToTop: true
  profileMode:
    enabled: true
  socialIcons:
    - name: linkedin
      url: 'https://linkedin.com/in/jozefcipa'
    - name: github
      url: 'https://github.com/jozefcipa'
menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 1
    - identifier: work
      name: work
      url: /work
      weight: 2
    - identifier: about
      name: about
      url: /about
      weight: 3
    - identifier: blog
      name: blog
      url: /blog
      weight: 4
    - identifier: projects
      name: projects
      url: /projects
      weight: 5